### ISSUE TITLE
"undefined symbol: __sync_add_and_fetch_8' (load_failed)" on mips, mipsel and powerpc

### ISSUE THREAD

**Issue by debalance** [processone/cache_tab#12]
Hi,

on the architectures mips, mipsel and powerpc it is currently not possible to use cache_tab:
> =ERROR REPORT==== 14-Jul-2017::14:55:11 ===
Failed to load NIF /<<PKGBUILDDIR>>/priv/lib/ets_cache: Failed to load NIF library: '/<<PKGBUILDDIR>>/priv/lib/ets_cache.so: undefined symbol: __sync_add_and_fetch_8' (load_failed)

You can access the full build logs here:
https://buildd.debian.org/status/package.php?p=erlang-p1-cache-tab&suite=sid

**Comment by debalance** [comment]
Somebody has created a patch to fix this: https://bugs.debian.org/868787
Haven't had time yet to test it though.

**Comment by zinid** [comment]
Everything is great, but libatomic dependence sucks.

**Comment by zinid** [comment]
I think the issue can be resolved by upgrading GCC. I close the issue.
