### ISSUE TITLE
Warning: crypto:rand_uniform/2 is deprecated and will be removed in a future release; use rand:uniform/1

### ISSUE THREAD

**Issue by joudinet** [processone/cache_tab#14]
Compiling with OTP 20.0, I get the following warning:

> Warning: crypto:rand_uniform/2 is deprecated and will be removed in a future release; use rand:uniform/1

I open this issue simply to inform you, in case you're not already aware of this future change. Feel free to close it.

**Comment by mremond** [comment]
It is fixed.
