### ISSUE TITLE
Make ejabberd 15.06 fail

### ISSUE THREAD

**Issue by emmanuel-florent** [processone/cache_tab#2]
How ro reproduce:
git clone https://github.com/processone/ejabberd.git --branch 15.06 ejabberd
cd ejabberd
 chmod +x ./autogen.sh
 ./autogen.sh 
./configure  --enable-user=$EJABBERD_USER --disable-tools --disable-pam
make

Error message:
....

usr/lib/erlang/bin/escript rebar get-deps && :> deps/.got
==> rel (get-deps)
==> ejabberd (get-deps)
Pulling p1_cache_tab from {git,"https://github.com/processone/cache_tab"}
Cloning into 'p1_cache_tab'...
ERROR: Dependency dir /usr/src/ejabberd/deps/p1_cache_tab failed application validation with reason:
{name_mismatch,{"/usr/src/ejabberd/deps/p1_cache_tab/src/cache_tab.app.src",
                {expected,p1_cache_tab},
                {has,cache_tab}}}.
ERROR: 'get-deps' failed while processing /usr/src/ejabberd: rebar_abort
make: *** [deps/.got] Error 1

My environment is docker container that was recently building fine.
[Dockerfile.txt](https://github.com/processone/cache_tab/files/49988/Dockerfile.txt)

 recently working fine.

**Comment by emmanuel-florent** [comment]
Fortunatly 15.11 make works

Add to get Erlang/OTP from:
 https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_18.1-1~ubuntu~precise_amd64.deb 

to get a correct Erlang version on ubuntu:trusty

I'm a big fan of your fantastic work !

**Comment by zinid** [comment]
Yes, 15.06 doesn't have tagged deps, so it may fail any time.

**Comment by mremond** [comment]
To compile older version of ejabberd you need to use `cache_tab` with tag "1.0.0". Newer version of `cache_tab` will be uncompliant.
