### ISSUE TITLE
Why we have cache_tab and ets_cache, what's the difference between them?

### ISSUE THREAD

**Issue by jerry-chao** [processone/cache_tab#23]
I am looking for erlang vm cache for Key-Value storage. But i cannot find the difference between the two implement cache_tab and ets_cache. Anyone can point this?

**Comment by prefiks** [comment]
You probably should be using ets_cache, it's  reimplementation of cache_tab but with multi node synchronization added (and a bit different underlying implementation)

**Comment by jerry-chao** [comment]
OK, I am trying to test est_cache. But I found some cases which is not the same.  cache_tab mayed cached the value and not access db, but ets_cache will.
Some sample code like this,

```erlang
  cache_tab:delete(appconfig_cache, test, fun() -> error end),
  lists:foreach(fun(_) ->
                        spawn(fun() -> cache_tab:lookup(appconfig_cache, test, fun() -> io:format("read from db"), {ok, test} end) end)
                end, lists:seq(1,10)).
```
this code only display `read from db` once

VS ets_cache
```erlang
    ets_cache:delete(appconfig_cache_ets, test),
    lists:foreach(fun(_) ->
                          spawn(fun() -> ets_cache:lookup(appconfig_cache_ets, test, fun() -> io:format("read from db ~n"), {ok, test} end) end)
                  end, lists:seq(1,10)).
```
this code will display `read from db` many times.

Anyway i will try ets_cache instead of cache_tab

**Comment by prefiks** [comment]
Indeed, that difference in implementation between those two, cache_tab serializes access to data (it's implemented as number of workers that process one operation at a time, and operation with same argument always choose same worker), while ets_cache operations are executed fully in parallel, so with it you may see that lookup functions can be called multiple times when there is no cached entry.

**Comment by jerry-chao** [comment]
thanks, I got it. I will try to use them in different scenario
