### ISSUE TITLE
Make ejabberd 13.12 fail

### ISSUE THREAD

**Issue by cisiqo** [processone/cache_tab#3]
ERROR: Dependency dir /home/ubuntu/ejabberd/deps/p1_cache_tab failed application validation with reason:
{name_mismatch,{"/home/ubuntu/ejabberd/deps/p1_cache_tab/src/cache_tab.app.src",
                {expected,p1_cache_tab},
                {has,cache_tab}}}.
ERROR: 'get-deps' failed while processing /home/ubuntu/ejabberd: rebar_abort
make: *** [deps/.got] Error 1

change the application name to p1_cache_tab of cache_tab.app.src it will be ok.

**Comment by mremond** [comment]
To compile older version of ejabberd you need to use `cache_tab` with tag "1.0.0". Newer version of `cache_tab` will be uncompliant.
