### ISSUE TITLE
Usage and understanding cache_opts

### ISSUE THREAD

**Issue by nOmi7** [processone/cache_tab#5]
lifetime  -- is 3600 by default does this means after 3600 it deleted the complete ETS tab or it just deletes all the entries from ets table which are not used for > 3600 

cache_missed - is true by default what does this mean ?

limit = 1000 be default after 1000 it deletes old entries which passed lifetime or deletes first inserted  or deletes all the entries  and re-puts the values ?

There is no function to update the cache element can this be taken as feature request to update the cache content for an Id . for now way is to do lookup then delete and then insert again. 
cache_missed = false is not updating the content for the primary key.

**Comment by zinid** [comment]
* First of all, the default `life_time` in `ets_cache` is `infinity`. When `life_time` is expired, it deletes all entries inserted `life_time` seconds ago. It doesn't check for usage, i.e. there is no [LRU](https://en.wikipedia.org/wiki/Cache_replacement_policies#LRU) support. Unlike `cache_tabe`, LRU is not supported in `ets_cache` intentionally, to keep the cache more efficient (avoiding additional inserts). Also, In my experience I didn't find benefits from using LRU.

* `cache_missed` means that if there is no data in the database associated with the key (i.e. the callback functions returns `error`), this 'miss' is also cached, so further database lookups (which will result in 'miss' again) will not be performed.

* When `max_size` (not `limit`) is reached, in current implementation, all values are to be deleted. This is also done for reasons of efficiency: in practice, if `max_size` is reached, most likely this means it will be reached soon again and again and again, so it's pointless to shrink only half of the cache or so.

**Comment by nOmi7** [comment]
@zinid  thanks how do i update the data for existing key ? I have requirement where for ge pri key 1 -- had name abc need to be updated to xyz when update occurs ? how can be updates achieved.

**Comment by zinid** [comment]
Can't you just write the new data into database and delete it from cache? New lookups will cache up the new value.

**Comment by nOmi7** [comment]
Well I can definitely do it and in fact i do write it to the DB however to avoid additional select i/o to db  was thinking to update the cache

**Comment by zinid** [comment]
I don't think you gather a lot of benefits from this, I personally don't bother.

**Comment by nOmi7** [comment]
Hmm ok i can use it that way then idk but can we add update as feature request tho ?

**Comment by zinid** [comment]
Well, I will try to think about this a bit, if I find a cheap way to maintain consistency (without adhoc merging protocol and maintanence of "tombstones" - this is needed because we update cache on all nodes optimistically) then I will implement this.

**Comment by zinid** [comment]
OK, we can insert the new value into cache locally and delete it on other nodes. This will not require any merging/tombstones. But if we need to insert the new value on all nodes, this will definitely require tombstones maintenance.

**Comment by nOmi7** [comment]
Thanks @zinid

**Comment by nOmi7** [comment]
Please review to see if i can create a pull request 
```
-spec update(atom(), any(), read_fun()) -> {ok, any()} | error.
update(Name, Key, UpdateFun) ->
  Value = UpdateFun(),
	try ets:lookup(Name, Key) of
		[{_, Value, ExpireTime}] ->
			if is_integer(ExpireTime) ->
				case ExpireTime > current_time() of
					true -> Value;
					false ->
						ets:delete_object(Name, {Key, Value, ExpireTime}),
						do_lookup(Name, Key, UpdateFun)
				end;
				true ->
					Value
			end;
		[{_, OldValue, ExpireTime}] ->
      ets:delete_object(Name, {Key, OldValue, ExpireTime}),
      do_lookup(Name, Key, UpdateFun);
		[] ->
			do_lookup(Name, Key, UpdateFun);
		_ ->
			Value
	catch _:badarg ->
		Value
	end.

```


Test  cases

rd(user,{id,name}).
U1 = #user{id = 1,name = "jeet"}. 
U2 = #user{id = 2,name = "zinid"}.    
U3 = #user{id = 3,name = "toupdate"}.
ets_cache:new(test_update,[]).

 ets_cache:lookup(test_update,1,fun () -> U1 end).
ets_cache:lookup(test_update,2,fun () -> U2 end).
 ets_cache:lookup(test_update,3,fun () -> U3 end).


(ejabberd@localhost)32> ets:tab2list(test_update).                                                  
[**{1,#user{id = 1,name = "jeet"},infinity},**
 {3,#user{id = 3,name = "toupdate"},infinity},
 **{2,#user{id = 2,name = "zinid"},infinity}**]


ets_cache:update(test_update,1,fun () -> U1#user{name = "updatedjeet"} end)
 ets_cache:update(test_update,2,fun () -> U2#user{name = "updatedzinid"} end).

 ets:tab2list(test_update).                                                   
[**{1,#user{id = 1,name = "updatedjeet"},infinity}**,
 {3,#user{id = 3,name = "toupdate"},infinity},
 **{2,#user{id = 2,name = "updatedzinid"},infinity}**]

**Comment by zinid** [comment]
The old value should be also deleted on other nodes, otherwise we would get stale cache on peer nodes.

**Comment by nOmi7** [comment]
replaced ets:delete_object(Name, {Key, Value, ExpireTime}), with delete(Name, Key) to delete from all nodes ?
Shouild i create a pull request for the same or you will add it from the issue logs , Is it good to be in ejabberd mainstream (definately will feel proud about it :))

**Comment by zinid** [comment]
Feel free to create a PR, I will merge it if it's good enough.
