### ISSUE TITLE
How to ?

### ISSUE THREAD

**Issue by nOmi7** [processone/cache_tab#8]
Hello How to restrict a cache to be on one node only in a cluster  there are some caches which we dont want to be distributed how can we achieve it on only one node ?

**Comment by zinid** [comment]
This is the default behaviour actually: just don't provide `Nodes` argument, or set it to `[node()]`.

**Comment by nOmi7** [comment]
Okay ... also currently there is no hook/fun when a cache_element is evicted due to expiry.
For eg: if my cache has element (1,2,3) on next operation it check for expiry and say 3 is expired so it just removes it . 
Can there be mechanism where if its getting deleted or removed due to expiry it should write to DB sometimes i am not using update func to write to db before cache update as i have very freq updates one table so i update it only on session termination but there is no mechanism if the cache element is removed due to time expiry it should write to db.

I hope i was able to explain it.

**Comment by zinid** [comment]
It seems like what you basically want is something like [fsync](https://en.wikipedia.org/wiki/Sync_%28Unix%29). No, it's not implemented, and I'm not sure this should be implemented (at least the way you want it to be implemented, i.e. fsync on expired items).

**Comment by zinid** [comment]
On the other hand, `fsync` functionality looks attractive, I will think about it.

**Comment by nOmi7** [comment]
Cool thanks
